### ISSUE TITLE
`ImportError` for `scikit_learn` >= 1.0.0

### ISSUE THREAD

**Issue by matchy233** [Teichlab/bbknn#54]
We are currently trying to import `DistanceMetrics` from `sklearn.neighbors` in `bbknn/matrix.py` ([link to code](https://github.com/Teichlab/bbknn/blob/4b11a887a2a51a33030a86844f0d2371b9278447/bbknn/matrix.py#L13)) but this is only possible for `scikit_learn<1.0.0`. `DistanceMetrics` is moved to `sklearn.metric` in the later versions of `sklearn`. 

I will raise a PR for fixing this via handling the `ImportError` -- but would like to hear opinions from the maintainers for sure!

**Comment by ryan-williams** [comment]
`sklearn.neighbors.DistanceMetric` was removed in sklearn 1.3.0 ([released 2023-06-30](https://pypi.org/project/scikit-learn/1.3.0/); [here it is in 1.2.2](https://github.com/scikit-learn/scikit-learn/blob/9aaed498795f68e5956ea762fef9c440ca9eb239/sklearn/neighbors/__init__.py#L23), [gone in 1.3.0](https://github.com/scikit-learn/scikit-learn/blob/1.3.0/sklearn/neighbors/__init__.py), [removal commit](https://github.com/scikit-learn/scikit-learn/commit/6b332d9969be7bb57aef1488bae89ece75fd05ad)).

Seems like you're supposed to use [`sklearn.metrics.DistanceMetric`, which is present since sklearn 1.0.2](https://github.com/scikit-learn/scikit-learn/blob/1.0.2/sklearn/metrics/__init__.py#L39).

A fix here could be to update [the import](https://github.com/Teichlab/bbknn/blob/4b11a887a2a51a33030a86844f0d2371b9278447/bbknn/matrix.py#L13), and constrain [the `sklearn` requirement](https://github.com/Teichlab/bbknn/blob/4b11a887a2a51a33030a86844f0d2371b9278447/pyproject.toml#L20) to `>=1.0.2`.

**Comment by ryan-williams** [comment]
For easier searching, the error that led me here was:

```python
from sklearn.neighbors import DistanceMetric
# ImportError: cannot import name 'DistanceMetric' from 'sklearn.neighbors' (…/lib/python3.9/site-packages/sklearn/neighbors/__init__.py)
```

You either have to pin `scikit-learn<1.3`, or change the import:

```diff
-from sklearn.neighbors import DistanceMetric
+from sklearn.metrics import DistanceMetric
```

**Comment by ktpolanski** [comment]
Thank you both for bringing this to my attention. I've merged Ryan's pull request (sklearn 1.0.2 is over a year old at this point so it feels okay to require it), but will credit you both in the change log.

**Comment by bio-la** [comment]
Hi, thanks for the timely fix! please note that this is still an issue if installing bbknn from conda or pip.

**Comment by ktpolanski** [comment]
I think I pretty much just have docstring updates left in terms of tying up loose ends.

**Comment by ktpolanski** [comment]
Alright, 1.6.0 is now live on pip!

**Comment by bio-la** [comment]
it seems something is not right cause trying to run it after installation from pip results in segmentation fault.
no other error messages are issued and I'm working on a subset of ~2000 cells so i don't really think it's a memory issue.
any idea what to check? thanks @ktpolanski !!

**Comment by ktpolanski** [comment]
It's probably annoy acting up. Try to run with `computation="cKDTree"` and/or install a different annoy version

**Comment by bio-la** [comment]
yes i somehow was breaking some dependencies, i installed all in a new conda env and it works. 
`WARNING: consider updating your call to make use of `computation` ` is indeed sorted with "cKDTree" (but not if calling bbknn from `scanpy.external` so that might need updating) thank you!
